apiVersion: apps/v1
kind: Deployment
metadata:
   name: super-mario-app
   labels:
      app: super-mario-app
spec:
   replicas: 1
   selector:
      matchLabels:
         app: super-mario-app
   template:
      metadata:
         labels:
            app: super-mario-app
      spec:
          containers:
           -  name: super-mario-app
              image: kaminskypavel/mario
              ports:
              - containerPort: 8080
              resources:
               limits:
                  memory: "256Mi"
                  cpu: "250m"
               requests:
                  memory: "128Mi"
                  cpu: "100m"