apiVersion: apps/v1
kind: Deployment
metadata:
   name: mario-game
   labels:
      app: mario-game
spec:
   replicas: 1
   selector:
      matchLabels:
         app: mario-game
   template:
      metadata:
         labels:
            app: mario-game
      spec:
          containers:
           -  name: mario-game
              image: docker.io/pengbai/docker-supermario:latest
              ports:
              - containerPort: 8080
              resources:
               limits:
                  memory: "256Mi"
                  cpu: "250m"
               requests:
                  memory: "128Mi"
                  cpu: "100m" 