apiVersion: v1
kind: Service
metadata:
  name: mario-service
spec:
  type: NodePort
  selector:
    app: mario-game
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080

      