apiVersion: v1
kind: Service
metadata:
  name: super-mario-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "classic"
spec:
  type: LoadBalancer
  selector:
    app: super-mario-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

      